services:
  postgres:
    image: postgres:16
    environment:
      postgres_USER: postgres_ep1
      postgres_PASSWORD: P@ssw0rd_ep1
      postgres_DB: DB_project_ep1
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    
volumes:
  postgres_data:


networks:
  app-network: